//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VENTAS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Compra
    {
        public int id_detalle_compra { get; set; }
        public int id_compra { get; set; }
        public int id_producto { get; set; }
        public int id_proveedor { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<decimal> precio { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
